---
- name: Set package and ini path for Debian/Ubuntu
  set_fact:
    php_packages: "{{ php_packages_debian }}"
    php_ini_path: "{{ php_ini_path_debian }}"

- name: Install PHP and modules from Debian/Ubuntu 
  ansible.builtin.package:
    name: "{{ php_packages }}"
    state: present
    update_cache: yes 

- name: Deploy PHP configuration
  ansible.builtin.template:
    src: php.ini.j2
    dest: "{{ php_ini_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache
