---
- name: Set package and ini path for RedHat/CentOS
  set_fact:
    php_packages: "{{ php_packages_redhat }}"
    php_ini_path: "{{ php_ini_path_redhat }}"

- name: Install PHP and modules
  ansible.builtin.package:
    name: "{{ php_packages }}"
    state: present
  become: yes

- name: Deploy PHP configuration
  ansible.builtin.template:
    src: php.ini.j2
    dest: "{{ php_ini_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache
  become: yes
